/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface MatchData {
	matchInfo: string;
	teamA: string;
	teamB: string;
	scoreA: number;
	scoreB: number;
	matchColor: ColorInfo;
	swapColor: boolean;
}
export interface ColorInfo {
	index: number;
	name: string;
	teamA: string;
	teamB: string;
}
