/* prettier-ignore */
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Socials = SocialsGroup[];

export interface SocialsGroup {
	name: string;
	items: SocialItem[];
}
export interface SocialItem {
	platform: 'Bluesky' | 'Discord' | 'Twitter' | 'YouTube';
	social: string;
}
